apiVersion: v1
kind: Secret
metadata:
  name: observer-secret
type: Opaque
stringData:
  client_id: YOUR_CLIENT_ID
  client_secret: YOUR_CLIENT_SECRET
  username: YOUR_USERNAME
  password: YOUR_PW
---
apiVersion: v1
kind: Service
metadata:
  name: observer
  labels:
    app: observer
spec:
  type: NodePort
  ports:
    - port: 3000
      name: grafana
      nodePort: 30001
      protocol: TCP
  selector:
    app: observer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: observer
spec:
  selector:
    matchLabels:
      app: observer
  template:
    metadata:
      labels:
        app: observer
    spec:
      containers:
        - name: telegraf
          image: 'floak/telatmo:latest'
          env:
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: observer-secret
                  key: client_id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: observer-secret
                  key: client_secret
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: observer-secret
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: observer-secret
                  key: password
        - name: influxdb
          image: 'influxdb:1.8'
          ports:
            - name: influxdb-port
              containerPort: 8086
        - name: grafana
          image: 'grafana/grafana:8.1.5'
          ports:
            - name: grafana-port
              containerPort: 3000

